# Generated by Django 3.2.7 on 2022-01-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_port',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock_port',
            name='quantity',
            field=models.TextField(null=True),
        ),
    ]
