# Generated by Django 3.2.7 on 2022-02-18 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_crypto_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_port',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock_port',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crypto_port',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_port',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
